"""Run a batch of experiments headless and regenerate the experiment log.

    python3 batch.py                 # default plan below
    python3 batch.py --full          # full step budgets (default is quick: half the steps)
    python3 batch.py --memory        # let runs read and write long-term memory (default off: runs stay independent)
    python3 batch.py --sweep         # Δ sweep instead: architecture, Δ 0 / .25 / .5 / .75 / 1, two seeds each
    python3 batch.py --report        # only rewrite EXPERIMENTS.md from runs/

Reasoners run one LLM call at a time with a cooldown (APORIA_COOLDOWN); expect a few minutes per run.
"""

from __future__ import annotations

import json
import sys
import time
import traceback
from pathlib import Path

ROOT = Path(__file__).parent
QUESTIONS = [
    "Is personal identity dependent on psychological continuity?",
    "Can a machine that only manipulates symbols genuinely understand anything?",
    "Is moral responsibility compatible with determinism?",
]
PLAN = (  # same question across conditions first, then Δ, then other questions
    [(QUESTIONS[0], c, 1.0) for c in ("architecture", "base", "prompt", "model")]
    + [(QUESTIONS[0], "architecture", d) for d in (0.0, 0.5)]
    + [(q, "architecture", 1.0) for q in QUESTIONS[1:]]
)
SWEEP = [(QUESTIONS[0], "architecture", d) for d in (0.0, 0.25, 0.5, 0.75, 1.0) for _ in range(2)]
KEYS = ["semantic_diversity", "branch_diversity", "disagreement_rate", "path_similarity", "conclusion_similarity",
        "unique_hypotheses", "unique_assumptions", "unique_objections"]


def report():
    runs = [json.loads(f.read_text()) for f in sorted((ROOT / "runs").glob("*.json"))]
    runs = [r for r in runs if "per_agent" in r["metrics"]]  # v2 runs only
    from metrics import failed
    for r in runs:  # runs saved before the server flagged them
        r.setdefault("failed", failed(r["agents"]))
    lines = ["# Experiment log", "", "Generated by `python3 batch.py --report` from `runs/`. One row per run of five reasoners.", "",
             "| run | condition | Δ | question | " + " | ".join(k.replace("_", " ") for k in KEYS) + " | stances |",
             "|" + "---|" * (len(KEYS) + 5)]
    for r in runs:
        st = ", ".join(f"{a[:3]} {s['conclusion']['stance']} {s['conclusion']['credence']:.2f}" for a, s in r["agents"].items())
        lines.append(f"| {r['id']}{' (failed: ' + ', '.join(r['failed']) + ')' if r['failed'] else ''} | {r['condition']} | {r['delta']} | {r['question'][:50]} | "
                     + " | ".join(str(r["metrics"][k]) for k in KEYS) + f" | {st} |")
    lines += ["", "## Research process per reasoner", "",
              "| run | reasoner | steps | hypotheses | rejected | experiments | defeats | resolution | info gain/step | tools | recalls | top compute |",
              "|---|---|---|---|---|---|---|---|---|---|---|---|"]
    for r in runs:
        for a, p in r["metrics"]["per_agent"].items():
            top = ", ".join(f"{k} {v:.0%}" for k, v in list(p["compute"].items())[:3])
            lines.append(f"| {r['id']} | {a} | {p['steps']} | {p['hypotheses']} | {p['rejected_hypotheses']} | {p['experiments']} | "
                         f"{p['defeats']} | {p['resolution_rate']} | {p['gain_per_step']} | {p['tool_calls']} | {p['recalls']} | {top} |")
    failures = [(r["id"], a, s["conclusion"].get("error") or f"{s.get('failed_calls')} LLM calls returned nothing")
                for r in runs for a, s in r["agents"].items()
                if s["conclusion"].get("error") or s.get("failed_calls") or len(s["history"]) <= 1]
    lines += ["", "## Failures (automatic)", ""] + ([f"- {i} {a}: {e}" for i, a, e in failures] or ["None recorded."])
    old = (ROOT / "EXPERIMENTS.md").read_text() if (ROOT / "EXPERIMENTS.md").exists() else ""
    notes = old[old.index("## Notes"):] if "## Notes" in old else "## Notes\n\nHand-written findings go here; regeneration keeps this section.\n"
    (ROOT / "EXPERIMENTS.md").write_text("\n".join(lines) + "\n\n" + notes)


if __name__ == "__main__":
    if "--report" not in sys.argv:
        import server
        import engine
        plan = SWEEP if "--sweep" in sys.argv else PLAN
        from metrics import failed
        done = set()
        for f in (ROOT / "runs").glob("*.json"):
            r = json.loads(f.read_text())
            if not (r.get("failed") or failed(r["agents"])):
                done.add((r["question"], r["condition"], r["delta"], r.get("seed"), bool(r.get("quick")), r["models"][0]))
        for k, (q, cond, d) in enumerate(plan):
            if not engine.alive():  # a dropped tunnel would otherwise record empty runs for the rest of the plan
                print(f"LLM endpoint {engine.OLLAMA} unreachable: stopping before run {k + 1}", flush=True)
                break
            t = time.time()
            seed = 1000 + (k % 2 if "--sweep" in sys.argv else k)  # the sweep pairs seeds across Δ levels
            if (q, cond, d, seed, "--full" not in sys.argv, server.model_plan(cond, d)[0]) in done:  # valid run exists: resume
                continue
            print(f"[{k + 1}/{len(plan)}] {cond} Δ={d} {q}", flush=True)
            try:
                m = server.run_experiment(server.Job(), q, cond, d, seed, {"run": 0, "runs": 1}, "--full" not in sys.argv,
                                         "readwrite" if "--memory" in sys.argv else "off")
                print("   ", {x: m[x] for x in KEYS}, f"{time.time() - t:.0f}s", flush=True)
            except Exception:
                traceback.print_exc()
            report()
    report()
