"""Export recorded runs for the static site (docs/, served by GitHub Pages).

    python3 export_site.py [runs dir]     # default: lab/runs

Writes docs/data/index.json (one row per run), docs/data/runs/<id>.json (the full record, for replay)
and copies the lab UI into docs/lab/, where it replays runs when no lab server answers.
Failed runs (a reasoner's LLM calls mostly came back empty) are exported and marked, never analysed.
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from metrics import failed

LAB = Path(__file__).parent
DOCS = LAB.parent / "docs"


def main(src: Path):
    runs = [json.loads(f.read_text()) for f in sorted(src.glob("*.json"))]
    runs = [r for r in runs if "per_agent" in r.get("metrics", {})]
    out = DOCS / "data" / "runs"
    out.mkdir(parents=True, exist_ok=True)
    rows = []
    for r in runs:
        r["failed"] = r.get("failed") or failed(r["agents"])
        (out / f"{r['id']}.json").write_text(json.dumps(r, separators=(",", ":")))
        m = r["metrics"]
        rows.append({k: r.get(k) for k in ("id", "question", "condition", "delta", "models", "seed", "quick", "failed")}
                    | {"metrics": {k: v for k, v in m.items() if not isinstance(v, dict)},
                       "per_agent": m["per_agent"],
                       "stances": {a: {k: (s["conclusion"] or {}).get(k) for k in ("stance", "credence", "position")}
                                   for a, s in r["agents"].items()}})
    ok = [x for x in rows if not x["failed"]]
    # the run the site opens first: the largest model's full architecture run at the highest Δ
    best = max(ok, key=lambda x: ("30b" in (x["models"] or [""])[0], x["condition"] == "architecture", x["delta"], not x["quick"]),
               default=None)
    (DOCS / "data" / "index.json").write_text(json.dumps({"featured": best and best["id"], "runs": rows}, indent=1))
    shutil.copytree(LAB / "static", DOCS / "lab", dirs_exist_ok=True)
    if best:
        readme_results(ok, best)
    print(f"{len(rows)} runs exported ({len(rows) - len(ok)} failed), featured {best and best['id']}")


KEYS = [("path_similarity", "path similarity ↓"), ("branch_diversity", "branch diversity ↑"),
        ("semantic_diversity", "semantic diversity ↑"), ("unique_objections", "unique objections ↑"),
        ("unique_assumptions", "unique assumptions ↑"), ("disagreement_rate", "disagreement ↑"),
        ("conclusion_similarity", "conclusion similarity ↓")]


def readme_results(ok: list[dict], best: dict):
    """README results block, generated from the same rows as the site so the numbers never drift."""
    model = lambda r: (r["models"] or ["?"])[0] + (" (half budget)" if r["quick"] else "")
    g = model(best)
    same = [r for r in ok if model(r) == g]

    def rows(label, groups):
        out = [f"| {label} | runs | " + " | ".join(l for _, l in KEYS) + " |", "|---" * (len(KEYS) + 2) + "|"]
        for name, rs in groups:
            if rs:
                out.append(f"| {name} | {len(rs)} | " + " | ".join(
                    f"{sum(r['metrics'][k] for r in rs) / len(rs):.3g}" for k, _ in KEYS) + " |")
        return out

    conds = [(c, [r for r in same if r["condition"] == c and r["delta"] == 1]) for c in ("base", "prompt", "architecture", "model")]
    deltas = sorted({r["delta"] for r in same if r["condition"] == "architecture"})
    sweep = [(f"Δ {d}", [r for r in same if r["condition"] == "architecture" and r["delta"] == d]) for d in deltas]
    md = [f"## Results ({g}, one question, five reasoners per run)", "",
          "Generated by `python3 lab/export_site.py` from `lab/runs/`; failed runs are excluded. ↑/↓ = the direction "
          "that means more divergence.", "", "**Conditions at Δ 1**", ""] + rows("condition", conds)
    if len(deltas) >= 3:
        md += ["", "**Δ sweep, architecture condition**", ""] + rows("Δ", sweep)
    readme = LAB.parent / "README.md"
    text = readme.read_text()
    a, b = text.index("<!-- RESULTS -->") + len("<!-- RESULTS -->"), text.index("<!-- /RESULTS -->")
    readme.write_text(text[:a] + "\n" + "\n".join(md) + "\n" + text[b:])


if __name__ == "__main__":
    main(Path(sys.argv[1]) if len(sys.argv) > 1 else LAB / "runs")
